name: Document
on:
  push:
    branches:
      - master
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/KarrLab/pkg_utils.git#egg=pkg_utils
          pip install git+https://github.com/KarrLab/sphinxcontrib-googleanalytics.git#egg=sphinxcontrib_googleanalytics
          pip install git+https://github.com/KarrLab/wc_utils.git#egg=wc_utils
          python -m pip install -e .[docs]
      - name: Document
        run: |
          sphinx-apidoc ./biosimulations_format_utils -o ./docs/source/modules/
          sphinx-build ./docs/source/ ./docs/html/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Documentation "
          body: "Created documentation using sphinx"
          lables: Documentation
          branch: documentation
          assignees: bilalshaikh42
          reviewers: bilalshaikh42
